#!/usr/bin/env bash

PROFILE=$(autorandr --current)

case "$PROFILE" in
  laptop-only)
    MONITOR=eDP-1
    for i in $(seq 1 10)
    do
        i3-msg "[workspace=$i] move workspace to output ${MONITOR}"
    done
    ;;

  cs-two-screens)
    MONITOR=DP-1-3
    for i in $(seq 1 2 10)
    do
        i3-msg "[workspace=$i] move workspace to output ${MONITOR}"
    done

    MONITOR=DP-1-1
    for i in $(seq 2 2 10)
    do
        i3-msg "[workspace=$i] move workspace to output ${MONITOR}"
    done
    ;;

#   cs-three-screens)
#     i3-msg "workspace 1; move workspace to output eDP-1"
#     i3-msg "workspace 2; move workspace to output HDMI-1"
#     i3-msg "workspace 3; move workspace to output DP-1"
#     ;;

esac