#!/bin/sh

if [ "${1}" == "pre" ]; then
  # Do the thing you want before suspend
  echo "Suspending at $(date)..."
elif [ "${1}" == "post" ]; then
  # Do the thing you want after resume
  i3lock -d -c "#000000"
fi
