##
## KEYBINDINGS
##

# First modifier: GUI set $m shift + Mod4
set $m Mod4 + comma + apostrophe
# Second modifier: CTRL + GUI
set $m2 Ctrl + Mod4 + Mod1

# Use Mouse+$m to drag floating windows to their wanted position
floating_modifier $m

## MODES ##

set $mode_mode Modes
bindsym $m + m mode "$mode_mode"
mode "$mode_mode" {

  # splith/splitv
  # Windows are sized so that every window gets
  # an equal amount of space in the container.
  bindsym e layout toggle split
  bindsym h split h
  bindsym v split v

  # stacking
  # Only the focused window in the container is displayed.
  # You get a list of windows at the top of the container.
  bindsym s layout stacking

  # tabbed
  # The same principle as stacking, but the list of windows
  # at the top is only a single line which is vertically split.
  bindsym z layout tabbed

  # Mode selection
  bindsym f fullscreen toggle

  # Toggle floating/tiling
  bindsym space floating toggle

  # back to normal: Enter or Escape
  bindsym Return mode "default"
  bindsym Escape mode "default"
}

# RESIZE
bindsym $m + x mode "resize"
mode "resize" {
  # These bindings trigger as soon as you enter the resize mode

  bindsym r resize shrink width 10 px or 10 ppt
  bindsym t resize grow height 10 px or 10 ppt
  bindsym i resize shrink height 10 px or 10 ppt
  bindsym u resize grow width 10 px or 10 ppt

  bindsym Left resize shrink width 10 px or 10 ppt
  bindsym Down resize grow height 10 px or 10 ppt
  bindsym Up resize shrink height 10 px or 10 ppt
  bindsym Right resize grow width 10 px or 10 ppt

  # back to normal: Enter or Escape
  bindsym Return mode "default"
  bindsym Escape mode "default"
}

# WINDOW FOCUS / MOVEMENT

# Focus
bindsym $m + r focus left
bindsym $m + t focus down
bindsym $m + i focus up
bindsym $m + u focus right
bindsym $m + Left focus left
bindsym $m + Down focus down
bindsym $m + Up focus up
bindsym $m + Right focus right

# Move
bindsym $m2 + r move left
bindsym $m2 + t move down
bindsym $m2 + i move up
bindsym $m2 + u move right
bindsym $m2 + Left move left
bindsym $m2 + Down move down
bindsym $m2 + Up move up
bindsym $m2 + Right move right

# WORKSPACES

bindcode $m + 10 workspace $ws1
bindcode $m + 11 workspace $ws2
bindcode $m + 12 workspace $ws3
bindcode $m + 13 workspace $ws4
bindcode $m + 14 workspace $ws5
bindcode $m + 15 workspace $ws6
bindcode $m + 16 workspace $ws7
bindcode $m + 17 workspace $ws8
bindcode $m + 18 workspace $ws9
bindcode $m + 19 workspace $ws10

bindcode $m2 + 10 move container to workspace $ws1
bindcode $m2 + 11 move container to workspace $ws2
bindcode $m2 + 12 move container to workspace $ws3
bindcode $m2 + 13 move container to workspace $ws4
bindcode $m2 + 14 move container to workspace $ws5
bindcode $m2 + 15 move container to workspace $ws6
bindcode $m2 + 16 move container to workspace $ws7
bindcode $m2 + 17 move container to workspace $ws8
bindcode $m2 + 18 move container to workspace $ws9
bindcode $m2 + 19 move container to workspace $ws10

# BRIGHTNESS
bindsym XF86MonBrightnessDown exec "light -U 10"
bindsym XF86MonBrightnessUp exec "light -A 10"

# VOLUME
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +2%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -2%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle

# SCREEN SHOT
bindsym Print exec xfce4-screenshooter

# USE ROFI TO OPEN AN APPLICATION
bindsym $m + d exec rofi -show drun

# OPEN TERMINAL
bindsym $m + Return exec i3-sensible-terminal

#
# CRTICAL COMMANDS WHICH REQUIRE OTHER MODIFIER
#

# KILL FOCUSED WINDOW
bindsym $m + a kill

# RELOAD / RESTART
bindsym $m + c reload
bindsym $m + z restart
