##
## KEYBINDINGS
##

# First modifier: GUI
set $m Shift + Mod4

## MODES ##

# WINDOW FOCUS / MOVEMENT

# Focus
bindsym $m + r focus left
bindsym $m + t focus down
bindsym $m + i focus up
bindsym $m + u focus right

# Move
bindsym $m + h move left
bindsym $m + g move down
bindsym $m + y move up
bindsym $m + k move right

# Resize
bindsym $m + Left resize shrink width 10 px or 10 ppt
bindsym $m + Up resize grow height 10 px or 10 ppt
bindsym $m + Down resize shrink height 10 px or 10 ppt
bindsym $m + Right resize grow width 10 px or 10 ppt

# WORKSPACES

bindsym $m + q workspace $ws1
bindsym $m + c workspace $ws2
bindsym $m + o workspace $ws3
bindsym $m + p workspace $ws4
bindsym $m + w workspace $ws5
bindsym $m + j workspace $ws6
bindsym $m + m workspace $ws7
bindsym $m + d workspace $ws8
bindsym $m + v workspace $ws9
bindsym $m + f workspace $ws10

bindsym $m + F1 move container to workspace $ws1
bindsym $m + F2 move container to workspace $ws2
bindsym $m + F3 move container to workspace $ws3
bindsym $m + F4 move container to workspace $ws4
bindsym $m + F5 move container to workspace $ws5
bindsym $m + F6 move container to workspace $ws6
bindsym $m + F7 move container to workspace $ws7
bindsym $m + F8 move container to workspace $ws8
bindsym $m + F9 move container to workspace $ws9
bindsym $m + F10 move container to workspace $ws10

bindsym $m + a split h
bindsym $m + z split v

# Mode selection
bindsym $m + b fullscreen toggle

# Toggle floating/tiling
bindsym $m + space floating toggle

# USE ROFI TO OPEN AN APPLICATION
bindsym $m + n exec rofi -show drun

# OPEN TERMINAL
bindsym $m + e exec i3-sensible-terminal

#
# CRTICAL COMMANDS WHICH REQUIRE OTHER MODIFIER
#

# KILL FOCUSED WINDOW
bindsym $m + s kill

# RELOAD / RESTART
bindsym $m + x restart

# SCREEN SHOT
bindsym Print exec xfce4-screenshooter
