##
## KEYBINDINGS
##

set $gui Mod4

# Use Mouse+$gui to drag floating windows to their wanted position
floating_modifier $gui

# KILL FOCUSED WINDOW
bindsym $gui+Ctrl+a kill

# USE ROFI TO OPEN AN APPLICATION
bindsym $gui+d exec rofi -show drun

## MODES ##

# Mode selection
bindsym $gui+f fullscreen toggle
bindsym $gui+s layout stacking
bindsym $gui+z layout tabbed
bindsym $gui+e layout toggle split
bindsym $gui+Ctrl+space floating toggle

# Split mode selection
bindsym $gui+h split h
bindsym $gui+v split v

# change focus between tiling / floating windows
bindsym $gui+space focus mode_toggle

# RELOAD / RESTART
bindsym $gui+Ctrl+c reload
bindsym $gui+Ctrl+r restart

# QUIT I3
bindsym $gui+Ctrl+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# RESIZE
bindsym $gui+r mode "resize"
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

# LOCK SCREEN
bindsym $gui+Ctrl+x exec . ~/.config/i3/i3-lock.sh

# OPEN TERMINAL
bindsym $gui+Return exec i3-sensible-terminal
bindsym $gui+Mod2+KP_Enter exec i3-sensible-terminal

# WINDOW FOCUS / MOVEMENT

# Focus
bindsym $gui+j focus left
bindsym $gui+k focus down
bindsym $gui+l focus up
bindsym $gui+m focus right
bindsym $gui+Left focus left
bindsym $gui+Down focus down
bindsym $gui+Up focus up
bindsym $gui+Right focus right

# Move
bindsym $gui+Ctrl+j move left
bindsym $gui+Ctrl+k move down
bindsym $gui+Ctrl+l move up
bindsym $gui+Ctrl+m move right
bindsym $gui+Ctrl+Left move left
bindsym $gui+Ctrl+Down move down
bindsym $gui+Ctrl+Up move up
bindsym $gui+Ctrl+Right move right

# WORKSPACES

bindcode $gui+10 workspace $ws1
bindcode $gui+11 workspace $ws2
bindcode $gui+12 workspace $ws3
bindcode $gui+13 workspace $ws4
bindcode $gui+14 workspace $ws5
bindcode $gui+15 workspace $ws6
bindcode $gui+16 workspace $ws7
bindcode $gui+17 workspace $ws8
bindcode $gui+18 workspace $ws9
bindcode $gui+19 workspace $ws10

bindcode $gui+Ctrl+10 move container to workspace $ws1
bindcode $gui+Ctrl+11 move container to workspace $ws2
bindcode $gui+Ctrl+12 move container to workspace $ws3
bindcode $gui+Ctrl+13 move container to workspace $ws4
bindcode $gui+Ctrl+14 move container to workspace $ws5
bindcode $gui+Ctrl+15 move container to workspace $ws6
bindcode $gui+Ctrl+16 move container to workspace $ws7
bindcode $gui+Ctrl+17 move container to workspace $ws8
bindcode $gui+Ctrl+18 move container to workspace $ws9
bindcode $gui+Ctrl+19 move container to workspace $ws10

# BRIGHTNESS

bindsym XF86MonBrightnessDown exec "light -U 10"
bindsym XF86MonBrightnessUp exec "light -A 10"

# VOLUME

bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +2%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -2%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle

bindsym $gui+Ctrl+semicolon exec pactl set-sink-volume @DEFAULT_SINK@ +2%
bindsym $gui+Ctrl+comma exec pactl set-sink-volume @DEFAULT_SINK@ -2%
bindsym $gui+Ctrl+colon exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle

# DISPLAY

bindsym $gui+Ctrl+d exec . $HOME/.mybin/display.sh

# SCREEN SHOT

bindcode KC_PRINT_SCREEN exec xfce4-screenshooter
