##
## KEYBINDINGS
##

# First modifier: GUI
set $m Mod4
# Second modifier: CTRL + GUI
set $m2 Ctrl + Mod4

set $notvm con_id="__focused__" title="^(?!moniere - Google Chrome).*"

# Use Mouse+$m to drag floating windows to their wanted position
floating_modifier $m

# set $script python3 ~/.dotfiles/config/i3/.config/i3/exec.py

###########
## MODES ##
###########

# Changing the container layout
bindsym $m + e [$notvm] layout toggle split
bindsym $m + s [$notvm] layout stacking
bindsym $m + t [$notvm] layout tabbed

bindsym $m + f [$notvm] fullscreen toggle
bindsym $m + space [$notvm] floating toggle

# Direct access for H and V
bindsym $m + h [$notvm] split h
bindsym $m + v [$notvm] split v



############
## RESIZE ##
############

bindsym $m + r [$notvm] mode "resize"
mode "resize" {
  # These bindings trigger as soon as you enter the resize mode
  bindsym Left resize shrink width 10 px or 10 ppt
  bindsym Down resize grow height 10 px or 10 ppt
  bindsym Up resize shrink height 10 px or 10 ppt
  bindsym Right resize grow width 10 px or 10 ppt

  # back to normal: Enter or Escape
  bindsym Return mode "default"
  bindsym Escape mode "default"
}


#############################
## WINDOW FOCUS / MOVEMENT ##
#############################

# Focus
bindsym $m + Left [$notvm] focus left
bindsym $m + Down [$notvm] focus down
bindsym $m + Up [$notvm] focus up
bindsym $m + Right [$notvm] focus right

# Move
bindsym $m2 + Left [$notvm] move left
bindsym $m2 + Down [$notvm] move down
bindsym $m2 + Up [$notvm] move up
bindsym $m2 + Right [$notvm] move right


################
## WORKSPACES ##
################

bindsym $m + 1 workspace $ws1
bindsym $m + 2 workspace $ws2
bindsym $m + 3 workspace $ws3
bindsym $m + 4 workspace $ws4
bindsym $m + 5 workspace $ws5
bindsym $m + 6 workspace $ws6
bindsym $m + 7 workspace $ws7
bindsym $m + 8 workspace $ws8
bindsym $m + 9 workspace $ws9
bindsym $m + 0 workspace $ws10

bindsym $m2 + 1 [$notvm] move container to workspace $ws1
bindsym $m2 + 2 [$notvm] move container to workspace $ws2
bindsym $m2 + 3 [$notvm] move container to workspace $ws3
bindsym $m2 + 4 [$notvm] move container to workspace $ws4
bindsym $m2 + 5 [$notvm] move container to workspace $ws5
bindsym $m2 + 6 [$notvm] move container to workspace $ws6
bindsym $m2 + 7 [$notvm] move container to workspace $ws7
bindsym $m2 + 8 [$notvm] move container to workspace $ws8
bindsym $m2 + 9 [$notvm] move container to workspace $ws9
bindsym $m2 + 0 [$notvm] move container to workspace $ws10


############
## SYSTEM ##
############

# BRIGHTNESS
bindsym XF86MonBrightnessDown exec "light -U 10"
bindsym XF86MonBrightnessUp exec "light -A 10"

# VOLUME
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +2%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -2%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle

# SCREEN SHOT
bindsym Print [$notvm] exec xfce4-screenshooter


##################
## APPLICATIONS ##
##################

# USE ROFI TO OPEN AN APPLICATION
bindsym $m + d [$notvm] exec rofi -show drun

# OPEN TERMINAL
bindsym $m + Return [$notvm] exec kitty

# KILL FOCUSED WINDOW (which are not VDI)
bindsym $m2 + k [$notvm] kill


#############
## DISPLAY ##
#############

# DISPLAY
bindsym $m2 + d exec . $HOME/.mybin/display.sh

# LOCK SCREEN
bindsym $m2 + x exec . $HOME/.config/i3/scripts/i3-lock.sh


###############
## I3 SYSTEM ##
###############

# RELOAD THE CONFIG / RESTART I3 INPLACE
bindsym $m2 + c reload
bindsym $m2 + r restart

# QUIT I3
bindsym $m2 + e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

