###############################
#            STARTUP          #
###############################

# Wallpaper
set $wallpaper ~/.dotfiles/Wallpaper/pepper-carrot-rain.jpg
# set $wallpaper ~/synology/home/Codes/dotfiles/Wallpaper/pepper-carrot-cosy.jpg
exec_always --no-startup-id feh --bg-scale $wallpaper
exec_always --no-startup-id /usr/libexec/gsd-xsettings

# WINDOW MANAGER APPLICATIONS
exec --no-startup-id compton
exec --no-startup-id nm-applet
exec --no-startup-id /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

