###############################
#            STARTUP          #
###############################

# Wallpaper
set $wallpaper ~/synology/home/Codes/dotfiles/Wallpaper/cats-bridge.jpg
# set $wallpaper ~/synology/home/Codes/dotfiles/Wallpaper/pepper-carrot-cosy.jpg
exec_always --no-startup-id feh --bg-scale $wallpaper
exec_always --no-startup-id /usr/libexec/gsd-xsettings

# WINDOW MANAGER APPLICATIONS
exec --no-startup-id compton
exec --no-startup-id xautolock -time 10 -corners -0-0 -locker '$HOME/.config/i3/scripts/i3-lock.sh'
exec --no-startup-id numlockx on
exec --no-startup-id indicator-sound-switcher
exec --no-startup-id synology-drive
exec --no-startup-id nm-applet
exec --no-startup-id /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id /usr/bin/syncthing -no-browser
exec --no-startup-id syncthingtray
exec --no-startup-id ibus exit

# RESTORE WORSPACES

# Workspace 1
exec --no-startup-id "i3-msg 'workspace 1; append_layout ~/.config/i3/config.d/layout.woodworker/workspace-1.json; exec firefox'"

# Workspace 2
exec --no-startup-id "i3-msg 'workspace 2; append_layout ~/.config/i3/config.d/layout.woodworker/workspace-2.json; exec keepassxc; exec kitty; exec thunderbird'"

# Workspace 3
exec --no-startup-id "i3-msg 'workspace 3; append_layout ~/.config/i3/config.d/layout.woodworker/workspace-3.json; exec code'"

# Workspace 5 and 8
exec --no-startup-id "i3-msg 'workspace 5; append_layout ~/.config/i3/config.d/layout.woodworker/workspace-5.json;'"
exec --no-startup-id "i3-msg 'workspace 8; append_layout ~/.config/i3/config.d/layout.woodworker/workspace-8.json; exec google-chrome;'"

# Workspace 10
exec --no-startup-id "i3-msg 'workspace 10; append_layout ~/.config/i3/config.d/layout.woodworker/workspace-10.json; exec obsidian;'"
