###############################
#            STARTUP          #
###############################

# Wallpaper
set $wallpaper ~/synology/home/Codes/dotfiles/Wallpaper/cats-bridge.jpg
# set $wallpaper ~/synology/home/Codes/dotfiles/Wallpaper/pepper-carrot-cosy.jpg
exec_always --no-startup-id feh --bg-scale $wallpaper
exec_always --no-startup-id /usr/libexec/gsd-xsettings

# WINDOW MANAGER APPLICATIONS
exec --no-startup-id compton
exec --no-startup-id xautolock -time 10 -corners -0-0 -locker '$HOME/.config/i3/scripts/i3-lock.sh'
exec --no-startup-id numlockx on
exec --no-startup-id indicator-sound-switcher
exec --no-startup-id synology-drive
exec --no-startup-id nm-applet
exec --no-startup-id /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

# RESTORE WORSPACES

# Workspace 1
exec i3-msg 'workspace 1'
exec firefox

# Workspace 2
exec thunderbird
exec keepassxc

# Workspace 3
exec i3-msg 'workspace 3'
exec code

# Switch back to workspace 1
exec i3-msg 'workspace 1'